package Servlet;

// Code partly generated by ChatGPT

import OOP.JOconnection;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet(name = "UserEdit", urlPatterns = {"/UserEdit"})
public class UserEdit extends HttpServlet {

    PreparedStatement ps = null;

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");

        try {
            
            String Name = request.getParameter("username");
            String Access = request.getParameter("access");

            try {
                JOconnection.JConnect();

                // Update the user information
                String sql = "UPDATE register SET access = ? WHERE username = ?";
                ps = JOconnection.conn.prepareStatement(sql);
                ps.setString(1, Access);
                ps.setString(2, Name);

                int status = ps.executeUpdate();
                if (status > 0) {
                    System.out.println("Updated");
                    System.out.println(Name);
                    System.out.println(Access);
                    response.sendRedirect("User.jsp");
                } else {
                    System.out.println("not update");
                    System.out.println(Name);
                    System.out.println(Access);
                }
            } catch (SQLException e) {
                System.out.println("Exception1: " + e);
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(UploadCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } finally {
                try {
                    if (ps != null) {
                        ps.close();
                    }
                    if (JOconnection.conn != null) {
                        JOconnection.conn.close();
                    }
                } catch (SQLException e) {
                    System.out.println(e);
                }
            }

        } catch (IOException e) {
            System.out.println("Exception2: " + e);
        }
    }
}
